# Format: category|target|quantity|price
lootbox|Base.LootBoxAmmo|1|5
lootbox|Base.LootBoxSpecialWeapon|1|25
lootbox|Base.LootBoxWeapon|1|15
lootbox|Base.LootBoxMelee|1|5
lootbox|Base.LootBoxClip|1|5
lootbox|Base.LootBoxAttachment|1|5
lootbox|Base.LootBoxClothes|1|5
survival|Base.Wire|1|10
survival|Base.NailsBox|1|30
survival|Base.ScrewsBox|1|45
survival|Base.Plank|1|4
survival|Base.Log|1|12
survival|Base.Glue|1|15
survival|Base.BucketConcreteFull|1|20
survival|Base.Generator|1|150
faction|Base.FactionsEconomy_Currency|1|1
farm|Base.GardenHoe|1|30
farm|Base.WateredCan|1|40
farm|Base.GardeningSprayEmpty|1|25
farm|Base.RoseBagSeed|1|5
farm|Base.PoppyBagSeed|1|5
farm|Base.LavenderBagSeed|1|5
farm|Base.CarrotBagSeed2|1|5
farm|Base.BroccoliBagSeed2|1|5
farm|Base.RedRadishBagSeed2|1|5
farm|Base.StrewberrieBagSeed2|1|5
farm|Base.TomatoBagSeed2|1|5
farm|Base.PotatoBagSeed2|1|5
farm|Base.CabbageBagSeed2|1|5
farm|Base.BarleyBagSeed|1|5
farm|Base.CornBagSeed|1|5
farm|Base.KaleBagSeed|1|5
farm|Base.RyeBagSeed|1|5
farm|Base.SweetPotatoBagSeed|1|5
farm|Base.GreenpeasBagSeed|1|5
farm|Base.OnionBagSeed|1|5
farm|Base.GarlicBagSeed|1|5
farm|Base.SoybeansBagSeed|1|5
farm|Base.SugarBeetBagSeed|1|5
farm|Base.WheatBagSeed|1|5
farm|Base.BasilBagSeed|1|5
farm|Base.ChamomileBagSeed|1|5
farm|Base.ChivesBagSeed|1|5
farm|Base.CilantroBagSeed|1|5
farm|Base.MarigoldBagSeed|1|5
farm|Base.OreganoBagSeed|1|5
farm|Base.ParsleyBagSeed|1|5
farm|Base.SageBagSeed|1|5
farm|Base.RosemaryBagSeed|1|5
farm|Base.ThymeBagSeed|1|5
farm|Base.LettuceBagSeed|1|5
farm|Base.BellPepperBagSeed|1|5
farm|Base.CauliflowerBagSeed|1|5
farm|Base.CucumberBagSeed|1|5
farm|Base.LeekBagSeed|1|5
farm|Base.LemonGrassBagSeed|1|5
farm|Base.ZucchiniBagSeed|1|5
farm|Base.WatermelonBagSeed|1|5
farm|Base.HabaneroBagSeed|1|5
farm|Base.JalapenoBagSeed|1|5
farm|Base.BlackSageBagSeed|1|5
farm|Base.BroadleafPlantainBagSeed|1|5
farm|Base.ComfreyBagSeed|1|5
farm|Base.CommonMallowBagSeed|1|5
farm|Base.HempBagSeed|1|5
farm|Base.HopsBagSeed|1|5
farm|Base.MintBagSeed|1|5
farm|Base.TurnipBagSeed|1|5
farm|Base.WatermelonBagSeed|1|5
farm|Base.WildGarlicBagSeed|1|5
farm|Base.PumpkinBagSeed|1|5
farm|Base.FlaxBagSeed|1|5
farm|Base.SpinachBagSeed|1|5
farm|Base.TobaccoBagSeed|1|5
farm|Base.SunflowerBagSeed|1|5
